"""add google oauth fields to users

Revision ID: 48d4d4c63a5d
Revises: 1575f6de2fe1
Create Date: 2026-09-30 13:35:09.673842

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "48d4d4c63a5d"
down_revision: Union[str, Sequence[str], None] = "1575f6de2fe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # add new columns
    op.add_column("users", sa.Column("google_id", sa.String(255), nullable=True))
    op.add_column("users", sa.Column("avatar_url", sa.String(500), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "profile_complete", sa.Boolean(), nullable=False, server_default="true"
        ),
    )  # ← add server_default

    # make existing columns nullable
    op.alter_column("users", "hashed_password", nullable=True)
    op.alter_column("users", "weight_kg", nullable=True)
    op.alter_column("users", "height_cm", nullable=True)
    op.alter_column("users", "age", nullable=True)
    op.alter_column("users", "gender", nullable=True)

    # add unique constraint for google_id
    op.create_unique_constraint("uq_users_google_id", "users", ["google_id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    # op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "gender", existing_type=sa.VARCHAR(length=10), nullable=False
    )
    op.alter_column("users", "age", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "users",
        "height_cm",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "users",
        "weight_kg",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "users", "hashed_password", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "profile_complete")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
